name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: [macos-latest, ubuntu-18.04] #, windows-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
        # we need fetch-depth 0 so setuptools_scm can resolve tags

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.3.0

    - name: Install Visual C++ for Python 2.7
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install vcpython27 -f -y

    - name: Build wheel
      run: |
        cd miniupnpc
        python -m cibuildwheel --output-dir dist
      env:
        # build python 3.7 and 3.8
        CIBW_BUILD: cp37-* cp38-*
        CIBW_BEFORE_BUILD: python -m pip install --upgrade pip
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: miniupnpc/dist
